from rapidfuzz import process, fuzz

OCCUPATIONS = [
    # Educação
    "Professor",
    "Professora",
    "Pedagogo",
    "Pedagoga",
    "Educador",
    "Educadora",
    "Monitor",
    "Monitora",
    "Coordenador pedagógico",
    "Coordenadora pedagógica",
    "Diretor escolar",
    "Diretora escolar",
    "Auxiliar de sala",
    "Estagiário",
    "Estagiária",

    # Saúde
    "Médico",
    "Médica",
    "Enfermeiro",
    "Enfermeira",
    "Técnico de enfermagem",
    "Técnica de enfermagem",
    "Auxiliar de enfermagem",
    "Dentista",
    "Cirurgião-dentista",
    "Farmacêutico",
    "Farmacêutica",
    "Fisioterapeuta",
    "Psicólogo",
    "Psicóloga",
    "Nutricionista",
    "Biomédico",
    "Biomédica",
    "Fonoaudiólogo",
    "Fonoaudióloga",
    "Terapeuta ocupacional",
    "Agente comunitário de saúde",
    "Agente de saúde",
    "Cuidador",
    "Cuidadora",
    "Cuidador de idosos",
    "Cuidadora de idosos",
    "Recepcionista hospitalar",

    # Administração e escritório
    "Administrador",
    "Administradora",
    "Analista",
    "Analista administrativo",
    "Assistente administrativo",
    "Auxiliar administrativo",
    "Secretário",
    "Secretária",
    "Recepcionista",
    "Atendente",
    "Contador",
    "Contadora",
    "Auxiliar contábil",
    "Gerente",
    "Supervisor",
    "Supervisora",
    "Coordenador",
    "Coordenadora",
    "Empresário",
    "Empresária",
    "Empreendedor",
    "Empreendedora",
    "Funcionário público",
    "Funcionária pública",
    "Servidor público",
    "Servidora pública",

    # Comércio e atendimento
    "Vendedor",
    "Vendedora",
    "Comerciante",
    "Caixa",
    "Operador de caixa",
    "Operadora de caixa",
    "Balconista",
    "Repositor",
    "Repositora",
    "Estoquista",
    "Promotor de vendas",
    "Promotora de vendas",
    "Representante comercial",
    "Consultor de vendas",
    "Consultora de vendas",
    "Feirante",
    "Ambulante",

    # Alimentação
    "Cozinheiro",
    "Cozinheira",
    "Auxiliar de cozinha",
    "Chef de cozinha",
    "Garçom",
    "Garçonete",
    "Barista",
    "Padeiro",
    "Padeira",
    "Confeiteiro",
    "Confeiteira",
    "Açougueiro",
    "Açougueira",
    "Churrasqueiro",

    # Serviços gerais e domésticos
    "Diarista",
    "Faxineiro",
    "Faxineira",
    "Empregado doméstico",
    "Empregada doméstica",
    "Doméstica",
    "Auxiliar de serviços gerais",
    "Servente",
    "Zelador",
    "Zeladora",
    "Porteiro",
    "Porteira",
    "Vigilante",
    "Segurança",
    "Babá",
    "Jardineiro",
    "Jardineira",
    "Dona de casa",
    "Do lar",

    # Beleza e cuidados pessoais
    "Cabeleireiro",
    "Cabeleireira",
    "Barbeiro",
    "Barbeira",
    "Manicure",
    "Pedicure",
    "Esteticista",
    "Maquiador",
    "Maquiadora",
    "Designer de sobrancelhas",
    "Massoterapeuta",

    # Agricultura e atividades rurais
    "Agricultor",
    "Agricultora",
    "Trabalhador rural",
    "Trabalhadora rural",
    "Lavrador",
    "Lavradora",
    "Produtor rural",
    "Produtora rural",
    "Pescador",
    "Pescadora",
    "Pecuarista",
    "Criador de animais",
    "Criadora de animais",

    # Transporte e entregas
    "Motorista",
    "Motorista de aplicativo",
    "Taxista",
    "Mototaxista",
    "Motoboy",
    "Entregador",
    "Entregadora",
    "Caminhoneiro",
    "Caminhoneira",
    "Cobrador",
    "Cobradora",

    # Construção e manutenção
    "Pedreiro",
    "Pedreira",
    "Servente de pedreiro",
    "Eletricista",
    "Encanador",
    "Encanadora",
    "Pintor",
    "Pintora",
    "Carpinteiro",
    "Carpinteira",
    "Marceneiro",
    "Marceneira",
    "Mecânico",
    "Mecânica",
    "Técnico em manutenção",
    "Técnica em manutenção",
    "Soldador",
    "Soldadora",

    # Tecnologia e engenharia
    "Programador",
    "Programadora",
    "Desenvolvedor",
    "Desenvolvedora",
    "Analista de sistemas",
    "Técnico em informática",
    "Técnica em informática",
    "Engenheiro",
    "Engenheira",
    "Engenheiro civil",
    "Engenheira civil",
    "Engenheiro de software",
    "Engenheira de software",
    "Arquiteto",
    "Arquiteta",

    # Direito, comunicação e outras áreas
    "Advogado",
    "Advogada",
    "Jornalista",
    "Fotógrafo",
    "Fotógrafa",
    "Designer",
    "Assistente social",
    "Policial",
    "Militar",
    "Bombeiro",
    "Bombeira",
    "Veterinário",
    "Veterinária",
    "Personal trainer",
    "Instrutor",
    "Instrutora",
    "Costureiro",
    "Costureira",
    "Artesão",
    "Artesã",

    # Outras respostas possíveis
    "Estudante",
    "Bolsista",
    "Autônomo",
    "Autônoma",
    "Trabalhador autônomo",
    "Trabalhadora autônoma",
    "Freelancer",
    "Aposentado",
    "Aposentada",
    "Desempregado",
    "Desempregada"
]
RELIGIONS = [
    # Religiões e tradições
    "Umbanda",
    "Umbandista",
    "Candomblé",
    "Candomblecista",
    "Judaísmo",
    "Judeu",
    "Judia",
    "Islamismo",
    "Islã",
    "Muçulmano",
    "Muçulmana",
    "Budismo",
    "Budista",
    "Hinduísmo",
    "Hinduísta",
    "Testemunha de Jeová",
    "Adventista",
    "Batista",
    "Metodista",
    "Presbiteriano",
    "Presbiteriana",
    "Pentecostal",
    "Neopentecostal",
    "Luterano",
    "Luterana",
    "Ortodoxo",
    "Ortodoxa",
    "Mórmon",
    "Santo dos Últimos Dias",
    "Messiânica",
    "Seicho-No-Ie",
    "Sikhismo",
    "Sikh",
    "Taoísmo",
    "Taoísta",
    "Xintoísmo",
    "Xintoísta",
    "Wicca",
    "Wiccano",
    "Wiccana",
    "Paganismo",
    "Pagão",
    "Pagã",
    "Quimbanda",
    "Jurema Sagrada",

    # Outras identificações e respostas possíveis
    "Ateu",
    "Ateia",
    "Ateísmo",
    "Agnóstico",
    "Agnóstica",
    "Agnosticismo",
    "Espiritualista",
    "Espiritualizado",
    "Espiritualizada",
    "Deísta",
    "Deísmo"
]

def suggestText(text: str, vocabulary: list[str]) -> dict:

    if not text or not text.strip() or not vocabulary:
        return {"sugestao": None, "similaridade": 0.0}

    result = process.extractOne(text, vocabulary, scorer=fuzz.WRatio)

    if result is None:
        return {
            "sugestao": None,
            "similaridade": 0.0
        }

    suggestion, similarity, _ = result

    return {
        "sugestao": suggestion,
        "similaridade": round(similarity, 2)
    }